# Generated by Django 4.2.7 on 2024-01-02 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tematy', '0003_alter_wpisy_options_tematy_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='wpisy',
            name='tytul',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tematy',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blog_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
