# Generated by Django 4.2.7 on 2024-01-02 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tematy', '0004_wpisy_tytul_alter_tematy_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wpisy',
            name='tytul',
        ),
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wybor', models.CharField(choices=[('like', 'Lubię to!'), ('dislike', 'Nie podoba mi się!')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wpis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tematy.wpisy')),
            ],
        ),
        migrations.AddField(
            model_name='wpisy',
            name='oceny',
            field=models.ManyToManyField(related_name='wpisy', to='tematy.ocena'),
        ),
    ]
