# Generated by Django 4.2.7 on 2024-01-02 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tematy', '0005_remove_wpisy_tytul_ocena_wpisy_oceny'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tematy',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
