# Generated by Django 4.2.7 on 2024-01-02 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tematy', '0007_alter_ocena_wpis_alter_wpisy_oceny'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wpisy',
            name='oceny',
        ),
        migrations.AlterField(
            model_name='tematy',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blog_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Ocena',
        ),
    ]
