# Generated by Django 4.2.7 on 2024-01-04 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tematy', '0009_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
